#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Motor,  port2,           leftTurn,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightTurn,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           leftPower,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rightPower,    tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//Custom map function
long map(long x, long in_min, long in_max, long out_min, long out_max) {
	return((x-in_min)*(out_max-out_min)/(in_max-in_min)+out_min);
}

task driveRightWheel() {
	float s = vexRT[Ch2]/vexRT[Ch1];
	float angle = map((atan(s)*(2/PI)),-1,1,-127,127);
	float speed = sqrt((vexRT[Ch1]*vexRT[Ch1])+(vexRT[Ch2]*vexRT[Ch2]));
	//This has to be bidder than 32, no more than 127
	int turningSpeed = 50;
	//tolerance should be kept realyyyyyyyy low below 4
	int tolerance = 1;
	//Motor go zoom
	motor[rightPower] = speed;
	//What is the current angle (0-359)
	int offAngle = SensorValue[rightEncoder]%360;
	//Do a thing untill it hits
	while(offAngle < angle + tolerance && offAngle > angle - tolerance) {
	//What is the current angle (0-359)
		offAngle = SensorValue[rightEncoder]%360;
		//Turn cc or ccc
		if(offAngle > 0) {
			motor[rightTurn] = turningSpeed;
		} else if(offAngle < 0) {
			motor[rightTurn] = -turningSpeed;
		}
	}
}

task driveLeftWheel() {
	float s = vexRT[Ch2]/vexRT[Ch1];
	float angle = map((atan(s)*(2/PI)),-1,1,-127,127);
	float speed = sqrt((vexRT[Ch1]*vexRT[Ch1])+(vexRT[Ch2]*vexRT[Ch2]));
	//This has to be bidder than 32, no more than 127
	int turningSpeed = 50;
	//tolerance should be kept realyyyyyyyy low below 4
	int tolerance = 1;
	//Motor go zoom
	motor[leftPower] = speed;
	//What is the current angle (0-359)
	int offAngle = SensorValue[leftEncoder]%360;
	//Do a thing untill it hits
	while(offAngle < angle + tolerance && offAngle > angle - tolerance) {
	//What is the current angle (0-359)
		offAngle = SensorValue[leftEncoder]%360;
		//Turn cc or ccc
		if(offAngle > 0) {
			motor[leftTurn] = turningSpeed;
		} else if(offAngle < 0) {
			motor[leftTurn] = -turningSpeed;
		}
	}
}

//Notes
//Joystick gives values between -127 and 127 inclusive.

task main() {
	while(true) {
		startTask(driveRightWheel);
		startTask(driveLeftWheel);
	}
}
